//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NintendoCDN_TicketParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NintendoCDN_TicketParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrmkDhRpdahLsbTz7O/Eew==.
        /// </summary>
        internal static string hmm1 {
            get {
                return ResourceManager.GetString("hmm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kKC7Hg6GSuh9E6agPSjJuA==.
        /// </summary>
        internal static string hmm2 {
            get {
                return ResourceManager.GetString("hmm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /7tXwU6Y7Gl1s4T89AeGtQ==.
        /// </summary>
        internal static string hmm3 {
            get {
                return ResourceManager.GetString("hmm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gJI3mbQfNqanX7i0jJX2bw==.
        /// </summary>
        internal static string hmm4 {
            get {
                return ResourceManager.GetString("hmm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pGmHrkfYK7T6irwEUChfpA==.
        /// </summary>
        internal static string hmm5 {
            get {
                return ResourceManager.GetString("hmm5", resourceCulture);
            }
        }
    }
}
